# Generated by Django 4.2.7 on 2023-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_account_alumniaccount_confirmstatus_groupaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
