# Generated by Django 4.2.7 on 2023-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_account_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatar/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/cover_avatar/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m'),
        ),
    ]
