# Generated by Django 4.2.7 on 2023-12-02 10:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_comment_comment_image_url_alter_account_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/accounts/avatar/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/accounts/cover_avatar/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/comments/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images/%Y/%m'),
        ),
    ]
