# Generated by Django 4.2.7 on 2023-12-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_alter_account_avatar_alter_account_cover_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsurvey',
            name='post_survey_status',
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='question_option_value',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
