# Generated by Django 4.2.7 on 2023-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_remove_postsurvey_post_survey_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='question_option_value',
            field=models.CharField(blank=True, default='Not input text type', max_length=10000, null=True),
        ),
    ]
