# Generated by Django 4.2.7 on 2023-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_alter_surveyanswer_question_option_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invitationaccount',
            name='post_invitation',
        ),
        migrations.RemoveField(
            model_name='surveyansweroption',
            name='survey_answer',
        ),
        migrations.RemoveField(
            model_name='surveyansweroption',
            name='survey_question_option',
        ),
        migrations.AddField(
            model_name='account',
            name='group_account',
            field=models.ManyToManyField(to='social_media.invitationgroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='invitation_account',
            field=models.ManyToManyField(to='social_media.postinvitation'),
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='survey_answer_option',
            field=models.ManyToManyField(to='social_media.surveyanswer'),
        ),
        migrations.DeleteModel(
            name='GroupAccount',
        ),
        migrations.DeleteModel(
            name='InvitationAccount',
        ),
        migrations.DeleteModel(
            name='SurveyAnswerOption',
        ),
    ]
