# Generated by Django 4.2.7 on 2023-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0009_remove_invitationaccount_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group_account',
            field=models.ManyToManyField(db_table='GroupAccount', to='social_media.invitationgroup'),
        ),
        migrations.AlterField(
            model_name='account',
            name='invitation_account',
            field=models.ManyToManyField(db_table='InvitationAccount', to='social_media.postinvitation'),
        ),
    ]
