# Generated by Django 4.2.7 on 2023-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0012_alter_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group_account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='invitation_account',
        ),
        migrations.AddField(
            model_name='invitationgroup',
            name='accounts',
            field=models.ManyToManyField(to='social_media.account'),
        ),
        migrations.AddField(
            model_name='postinvitation',
            name='account',
            field=models.ManyToManyField(to='social_media.account'),
        ),
    ]
