# Generated by Django 4.2.7 on 2023-12-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0013_remove_account_group_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postinvitation',
            old_name='account',
            new_name='accounts',
        ),
    ]
