# Generated by Django 4.2.7 on 2023-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0014_rename_account_postinvitation_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationgroup',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='social_media.account'),
        ),
        migrations.AlterField(
            model_name='postinvitation',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='social_media.account'),
        ),
    ]
