# Generated by Django 4.2.7 on 2023-12-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0015_alter_invitationgroup_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestionoption',
            name='survey_answer_option',
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='survey_answers',
            field=models.ManyToManyField(blank=True, to='social_media.surveyanswer'),
        ),
    ]
