# Generated by Django 4.2.7 on 2023-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0018_alter_account_deleted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='question_option_value',
            new_name='answer_value',
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
