# Generated by Django 4.2.7 on 2024-01-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0019_rename_question_option_value_surveyanswer_answer_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
