# Generated by Django 4.2.7 on 2024-01-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0023_alter_room_options_room_first_user_room_second_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='who_sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.account'),
        ),
    ]
