# Generated by Django 4.2.7 on 2024-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0024_alter_message_who_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='received_message_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
